const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Payment Schema
const paymentSchema = new Schema({
    bill: {
        type: Schema.Types.ObjectId,
        ref: 'Bill',
        required: [true, 'Bill reference is required'] // Reference to the bill associated with the payment
    },
    razorpay_order_id: {
        type: String,
        required: [true, 'Razorpay Order ID is required'] // Razorpay order ID for tracking
    },
    razorpay_payment_id: {
        type: String,
        required: [true, 'Razorpay Payment ID is required'] // Payment ID generated by Razorpay
    },
    payment_method: {
        type: String,
        required: [true, 'Payment method is required'] // Specifies how the payment was made (e.g., UPI, card)
    },
    status: {
        type: String,
        enum: ['created', 'captured', 'failed'],
        default: 'created' // Tracks the payment status
    },
    customer: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'Customer reference is required'] // Reference to the customer making the payment
    },
    provider: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'Provider reference is required'] // Reference to the provider receiving the payment
    },
    amount: {
        type: Number,
        required: [true, 'Amount is required'] // Payment amount in paise (1 INR = 100 paise)
    },
    platform_fee: {
        type: Number,
        default: 0 // Fee charged by the platform, optional
    },
    createdAt: {
        type: Date,
        default: Date.now // Timestamp for when the payment was created
    },
    updatedAt: {
        type: Date,
        default: Date.now // Timestamp for when the payment was last updated
    }
});

module.exports = mongoose.model('Payment', paymentSchema); // Export the Payment model